# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d94073072b77008cc571139c79c4ddaa"
name = "test-webhook-app"
handle = "test-webhook-app-7"
application_url = "https://chemicals-childhood-proxy-closest.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "learn-september.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders,read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://chemicals-childhood-proxy-closest.trycloudflare.com/auth/callback",
  "https://chemicals-childhood-proxy-closest.trycloudflare.com/auth/shopify/callback",
  "https://chemicals-childhood-proxy-closest.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "draft_orders/create",
  "draft_orders/update",
  "orders/create",
  "products/create"
]
  uri = "/webhooks"

[pos]
embedded = false
